spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update       # Crea o actualiza tablas automáticamente
    show-sql: true            # Muestra las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
